version: '3.8'

volumes:
  docker-volume:
  vendor-store:
  node_modules-store:

services:
  app:
    build: ./docker/php
    depends_on:
      - db
    links:
      - db
    volumes:
      - .:/var/www/hiro_universe:cached
      - vendor-store:/var/www/hiro_universe/vendor
      - node_modules-store:/var/www/hiro_universe/node_modules
    command: bash -c "php artisan serve --host 0.0.0.0" # 起動時にビルドインサーバーを起動
    ports:
      - "8000:8000"  # php artisan serve 用のポート
      - "8080:8080"  # HMR用のポート
    networks:
        - hiro-universe-dev
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3366:3306'
    environment:
      MYSQL_DATABASE: hiro_universe
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    volumes:
      - docker-volume:/var/lib/mysql
    networks:
      - hiro-universe-dev
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links: 
      - db:db
    ports:
      - 8888:80
    volumes:
      - ./docker/phpMyAdmin/phpmyadmin-misc.ini:/usr/local/etc/php/conf.d/phpmyadmin-misc.ini
    networks:
      - hiro-universe-dev

networks:
  hiro-universe-dev:
    external: true